DROP TABLE IF EXISTS direct_chat CASCADE;
DROP TABLE IF EXISTS message CASCADE;
DROP TABLE IF EXISTS user_chat_room CASCADE;
DROP TABLE IF EXISTS chat_room CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100)  NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_room (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(150) NOT NULL,
    room_type  VARCHAR(10)  NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_chat_room_type CHECK (room_type IN ('ROOM', 'DM'))
);

-- Универсальный уникальный индекс вместо partial index
CREATE UNIQUE INDEX ux_chat_room_room_name ON chat_room (room_type, name);

CREATE TABLE direct_chat (
    chat_room_id BIGINT NOT NULL PRIMARY KEY,
    user_low_id  BIGINT NOT NULL,
    user_high_id BIGINT NOT NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_direct_pair_order CHECK (user_low_id < user_high_id),
    CONSTRAINT fk_dc_room FOREIGN KEY (chat_room_id) REFERENCES chat_room (id) ON DELETE CASCADE,
    CONSTRAINT fk_dc_user_low FOREIGN KEY (user_low_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_dc_user_high FOREIGN KEY (user_high_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_direct_chat_pair ON direct_chat (user_low_id, user_high_id);

CREATE TABLE user_chat_room (
    user_id      BIGINT    NOT NULL,
    chat_room_id BIGINT    NOT NULL,
    joined_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_chat_room PRIMARY KEY (user_id, chat_room_id),
    CONSTRAINT fk_ucr_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ucr_room FOREIGN KEY (chat_room_id) REFERENCES chat_room (id) ON DELETE CASCADE
);

CREATE TABLE message (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT    NOT NULL,
    sender_id    BIGINT    NOT NULL,
    content      VARCHAR(1000) NOT NULL,
    sent_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_message_room FOREIGN KEY (chat_room_id) REFERENCES chat_room (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_message_room_sent_at ON message (chat_room_id, sent_at);

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='PUBLIC' ORDER BY TABLE_NAME;