name: 'SonarQube Analysis'
description: 'Run SonarQube analysis for pull request and push'
inputs:
  sonar-token:
    description: 'SonarQube authentication token'
    required: true
  project-key:
    description: 'SonarQube project key'
    required: true
  organization:
    description: 'SonarQube organization name'
    required: true
  host-url:
    description: 'SonarQube server URL'
    required: true
  binaries-path:
    description: 'Path to compiled Java binaries (target/classes)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven (skip tests)
      run: mvn clean install -DskipTests
      shell: bash

    - name: Run SonarQube analysis
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=${{ inputs.project-key }} \
          -Dsonar.organization=${{ inputs.organization }} \
          -Dsonar.host.url=${{ inputs.host-url }} \
          -Dsonar.java.binaries=${{ inputs.binaries-path }} \
          -Dsonar.login=${{ inputs.sonar-token }}
      shell: bash