-- schema.sql

-- Удаление таблиц (для повторных запусков при разработке)
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS user_chat_room;
DROP TABLE IF EXISTS chat_room;
DROP TABLE IF EXISTS users;

-- Таблица пользователей
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Таблица комнат (чатов)
CREATE TABLE chat_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Связь пользователь–комната (many-to-many)
CREATE TABLE user_chat_room (
    user_id     BIGINT NOT NULL,
    chat_room_id BIGINT NOT NULL,
    joined_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_chat_room PRIMARY KEY (user_id, chat_room_id),
    CONSTRAINT fk_user_chat_room_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_user_chat_room_room
        FOREIGN KEY (chat_room_id) REFERENCES chat_room (id)
            ON DELETE CASCADE
);

-- Таблица сообщений
CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    sender_id    BIGINT NOT NULL,
    content      VARCHAR(1000) NOT NULL,
    sent_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_message_room
        FOREIGN KEY (chat_room_id) REFERENCES chat_room (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_message_sender
        FOREIGN KEY (sender_id) REFERENCES users (id)
            ON DELETE CASCADE
);

-- Индексы для ускорения поиска
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_message_chat_room_id ON message (chat_room_id);
CREATE INDEX idx_message_sender_id ON message (sender_id);